// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using To_Do;

#nullable disable

namespace To_Do.Migrations
{
    [DbContext(typeof(dbAppContext))]
    partial class dbAppContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "7.0.3");

            modelBuilder.Entity("To_Do.Task", b =>
                {
                    b.Property<int>("TaskID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("taskChecked")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean");

                    b.Property<string>("taskCategory")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("taskDescription")
                        .HasColumnType("TEXT");

                    b.Property<string>("taskName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("TaskID");

                    b.ToTable("Task");
                });
#pragma warning restore 612, 618
        }
    }
}
